### ISSUE TITLE
Uncaught Error: spawn EACCES

### ISSUE THREAD

**Issue by hainuo** [Dgame/atom-php-fmt#6]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.11
**System**: Mac OS X 10.11
**Thrown From**: [php-fmt](https://github.com/Dgame/atom-php-fmt) package, v0.1.2
### Stack Trace

Uncaught Error: spawn EACCES

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:260

Error: spawn EACCES
  at exports._errnoException (util.js:734:11)
  at ChildProcess.spawn (child_process.js:1145:11)
  at Object.exports.spawn (child_process.js:977:9)
  at BufferedProcess.module.exports.BufferedProcess.spawn (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:188:44)
  at new BufferedProcess (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:52:14)
  at Object.module.exports.PhpFmt.transform (/Users/fengliu/.atom/packages/php-fmt/lib/php-fmt.coffee:150:23)
  at atom-workspace.subscriptions.add.atom.commands.add.php-fmt:transform (/Users/fengliu/.atom/packages/php-fmt/lib/php-fmt.coffee:70:89)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:245:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:184:20)

```
### Commands

```
  2x -3:38 core:backspace (input.hidden-input)
  5x -3:34.4.0 core:move-right (input.hidden-input)
     -3:31.8.0 core:save (input.hidden-input)
     -3:28.7.0 editor:log-cursor-scope (input.hidden-input)
     -2:28 grammar-selector:show (atom-text-editor.editor.editor-colors.is-focused)
     -2:16 core:move-right (input.hidden-input)
     -2:15.5.0 core:backspace (input.hidden-input)
  4x -2:10.6.0 core:move-left (input.hidden-input)
     -2:09.8.0 core:backspace (input.hidden-input)
  4x -2:08.7.0 core:move-right (input.hidden-input)
     -2:05.7.0 editor:consolidate-selections (input.hidden-input)
     -2:05.7.0 core:cancel (input.hidden-input)
  7x -1:36.1.0 core:backspace (input.hidden-input)
  4x -0:12.8.0 es6-javascript:wrap-block (input.hidden-input)
  8x -0:07.7.0 core:undo (input.hidden-input)
     -0:02.7.0 php-fmt:transform (input.hidden-input)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "git-diff",
      "language-ruby-on-rails",
      "language-shellscript",
      "open-on-github",
      "language-objective-c",
      "language-git"
    ],
    "themes": [
      "atom-dark-ui",
      "solarized-dark-syntax"
    ]
  },
  "php-fmt": {
    "noBackup": true,
    "lintBefore": true,
    "autoAlign": true,
    "php-bin": "/usr/local/bin/php",
    "phpExecutablePath": "/usr/local/",
    "useSpaceIndentation": true,
    "executablePath": "/usr/local/bin/fmt.phar",
    "configFile": "/User/fengliu/phpfmt.conf",
    "PSRNaming": true
  }
}
```
### Installed Packages

``` coffee
# User
atom-jsfmt, v0.8.3
atom-jsx-transform, v0.2.0
auto-encoding, v0.4.1
color-picker, v2.0.11
es6-javascript, v0.5.0
formatter, v2.12.3
git-control, v0.3.0
language-babel, v0.13.2
php-fmt, v0.1.2
react-snippets, v0.2.0
redux-snippets, v0.2.1

# Dev
No dev packages
```

**Comment by Dgame** [comment]
I'll investigate that.

**Comment by mbroo** [comment]
I get the same error on Mac OS 10.11 with Atom 1.0.19
